directive @rateLimit(
    max: Int,
    window: String,
    message: String,
    identityArgs: [String],
    arrayLengthField: String
) on FIELD_DEFINITION

directive @auth(
    requires: Role = USER
) on OBJECT | FIELD_DEFINITION

##################################

enum Role {
    ADMIN
    USER
}

type Token {
    token: String!
}

type TokenSet {
    token: String!
    refreshToken: String!
}

type User {
    id: Int!
    email: String!
    displayName: String!
    profilePicture: String!

}

## Query #########################

type Query {
    hello: String!
    user: User! @auth(requires: USER)
}

## Mutation ######################

type Mutation {
    register(captchaToken: String!, email: String!, displayName: String!, password: String!): TokenSet! @rateLimit(
        window: "5s",
        max: 10,
        message: "Too many requests"
    )

    login(captchaToken: String!, email: String!, password: String!): TokenSet! @rateLimit(
        window: "5s",
        max: 10,
        message: "Too many requests"
    )

    refreshToken(token: String!, refreshToken: String!): Token! @rateLimit(
        window: "5s",
        max: 10,
        message: "Too many requests"
    )
}